from cpgf.version import (
    APP_VERSION,
    BENCHMARK_VERSION,
    GEO_VERSION,
    JOINT_RETRIEVAL_FLOW_DIAGNOSTIC_V3_VERSION,
    JOINT_RETRIEVAL_FLOW_DIAGNOSTIC_VERSION,
    JOINT_RETRIEVAL_HOLDOUT_V3_VERSION,
    JOINT_RETRIEVAL_HOLDOUT_V4_VERSION,
    JOINT_RETRIEVAL_HOLDOUT_VERSION,
    KNOWLEDGE_VERSION,
    MOTOR_VERSION,
    PREPARATION_BASELINE_VERSION,
    PREPARATION_VERSION,
    RETRIEVAL_BENCHMARK_VERSION,
    RETRIEVAL_EVALUATION_VERSION,
    RETRIEVAL_FLOW_DIAGNOSTIC_VERSION,
    RETRIEVAL_PLANNER_HOLDOUT_VERSION,
    RETRIEVAL_PLANNER_VERSION,
    ROUTER_HOLDOUT_V2_VERSION,
    ROUTER_HOLDOUT_VERSION,
    ROUTER_VERSION,
    RULES_VERSION,
    SERVING_VERSION,
)


def test_methodology_versions():
    assert APP_VERSION == "0.22.0-dev"
    assert PREPARATION_BASELINE_VERSION == "1.0.0"
    assert PREPARATION_VERSION == "1.1.0"
    assert RULES_VERSION == "1.2.0"
    assert MOTOR_VERSION == "1.3.2"
    assert SERVING_VERSION == "1.5.0"
    assert GEO_VERSION == "1.1.0"
    assert KNOWLEDGE_VERSION == "1.2.0"
    assert BENCHMARK_VERSION == "1.0.0"
    assert RETRIEVAL_BENCHMARK_VERSION == "1.0.0"
    assert RETRIEVAL_EVALUATION_VERSION == "1.1.0"
    assert RETRIEVAL_PLANNER_VERSION == "1.3.0"
    assert RETRIEVAL_PLANNER_HOLDOUT_VERSION == "1.0.0"
    assert JOINT_RETRIEVAL_HOLDOUT_VERSION == "2.0.0"
    assert JOINT_RETRIEVAL_HOLDOUT_V3_VERSION == "3.0.0"
    assert JOINT_RETRIEVAL_HOLDOUT_V4_VERSION == "4.0.0"
    assert JOINT_RETRIEVAL_FLOW_DIAGNOSTIC_VERSION == "1.0.0"
    assert JOINT_RETRIEVAL_FLOW_DIAGNOSTIC_V3_VERSION == "1.0.0"
    assert RETRIEVAL_FLOW_DIAGNOSTIC_VERSION == "1.0.0"
    assert ROUTER_VERSION == "1.4.0"
    assert ROUTER_HOLDOUT_VERSION == "1.0.0"
    assert ROUTER_HOLDOUT_V2_VERSION == "2.0.0"
